brew "automake"
brew "desktop-file-utils"
brew "gobject-introspection"
brew "gtk-mac-integration"
brew "judy"
brew "meson"
brew "ninja"
brew "pkg-config"
brew "shared-mime-info"

tap "silimate/silimate"
brew "silimate/silimate/tcl-tk@8"
